### ISSUE TITLE
Let's create a better community

### ISSUE THREAD

**Issue by wootsbot** [react-next-boilerplate/react-next-boilerplate#52]
# Strategy 

React Next Boilerplate has launched 4 months ago, but it has been a work of more than a year of development according to the first commitment.

Very happy that the developer community is embracing this project in the best way and have the patience for the releases.

Currently, it is very difficult for me to send continuous improvements due to concentration on carrying out my tasks at work, so I'd like to receive more community PR and issues.

## 1. Grow organization
Would you like to be part of the organization?

- [x] :two_hearts: You are passionate about the open-source?.
- [x] :pray: Create 4 improvement issues for the project or bugs.
- [x] :pray:  Launches 4 PR of improvements or bugs that help the project and merge
- [x] :+1: Help the community with its issues

IF this happens, you will be welcome and receive free swag.

## 2. links to help you
- [x]  https://www.reactnextboilerplate.com/
- [x] [CONTRIBUTING.md](https://github.com/react-next-boilerplate/react-next-boilerplate/blob/canary/CONTRIBUTING.md)

**Comment by wootsbot** [comment]
Hi @cuongdevjs I would like to chat about the future of the organization in [discord](https://discord.gg/axV6J6a)

**Comment by cuongdevjs** [comment]
It's so awesome
